return {

    -- Deps
    "nvim-lua/plenary.nvim",

    -- Imported
    "arkav/lualine-lsp-progress",
    "nvim-lualine/lualine.nvim",
    "RRethy/nvim-base16",
    "folke/todo-comments.nvim",
    "hrsh7th/cmp-buffer",
    "hrsh7th/cmp-cmdline",
    "petertriho/cmp-git",
    "saadparwaiz1/cmp_luasnip",
    "hrsh7th/cmp-nvim-lsp",
    "hrsh7th/cmp-nvim-lsp-document-symbol",
    "hrsh7th/cmp-nvim-lsp-signature-help",
    "hrsh7th/cmp-nvim-lua",
    "hrsh7th/cmp-path",
    "f3fora/cmp-spell",
    "rafamadriz/friendly-snippets",
    "l3mon4d3/luasnip",
    "molleweide/LuaSnip-snippets.nvim",
    "hrsh7th/nvim-cmp",
    "numtostr/comment.nvim",
    "direnv/direnv.vim",
    "lukas-reineke/indent-blankline.nvim",
    "folke/trouble.nvim",
    "nvim-telescope/telescope.nvim",
    { "nvim-telescope/telescope-fzf-native.nvim", install = "make" },
    "nvim-telescope/telescope-project.nvim",
    "nvim-tree/nvim-tree.lua",
    "nvim-tree/nvim-web-devicons",
    "sindrets/diffview.nvim",
    { "tpope/vim-fugitive", lazy = false },
    "lewis6991/gitsigns.nvim",
    "tpope/vim-rhubarb",
    "folke/which-key.nvim",
    "nvim-neorg/neorg",
    "nvim-neorg/neorg-telescope",
    "onsails/lspkind.nvim",
    "jose-elias-alvarez/null-ls.nvim",
    "neovim/nvim-lspconfig",
    "smiteshp/nvim-navic",
    "b0o/SchemaStore.nvim",
    "echasnovski/mini.nvim",
    { "folke/neoconf.nvim", cmd = "Neoconf" },
    "folke/persistence.nvim",
}
