return {
    "folke/todo-comments.nvim",
    "hrsh7th/cmp-buffer",
    "hrsh7th/cmp-cmdline",
    "petertriho/cmp-git",
    "saadparwaiz1/cmp_luasnip",
    "hrsh7th/cmp-nvim-lsp",
    "hrsh7th/cmp-nvim-lsp-document-symbol",
    "hrsh7th/cmp-nvim-lsp-signature-help",
    "hrsh7th/cmp-nvim-lua",
    "hrsh7th/cmp-path",
    "f3fora/cmp-spell",
    "hrsh7th/nvim-cmp",
    "numtostr/comment.nvim",
    "direnv/direnv.vim",
    "lukas-reineke/indent-blankline.nvim",
    "folke/trouble.nvim",
    "onsails/lspkind.nvim",
    "jose-elias-alvarez/null-ls.nvim",
    "neovim/nvim-lspconfig",
    "echasnovski/mini.nvim",
    { "folke/neoconf.nvim", cmd = "Neoconf" },
    "folke/persistence.nvim",
}
