# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
}: {
  tree-sitter-eex = {
    pname = "tree-sitter-eex";
    version = "f742f2fe327463335e8671a87c0b9b396905d1d1";
    src = fetchFromGitHub {
      owner = "connorlay";
      repo = "tree-sitter-eex";
      rev = "f742f2fe327463335e8671a87c0b9b396905d1d1";
      fetchSubmodules = false;
      sha256 = "sha256-UPq62MkfGFh9m/UskoB9uBDIYOcotITCJXDyrbg/wKY=";
    };
  };
  tree-sitter-just = {
    pname = "tree-sitter-just";
    version = "8af0aab79854aaf25b620a52c39485849922f766";
    src = fetchFromGitHub {
      owner = "IndianBoy42";
      repo = "tree-sitter-just";
      rev = "8af0aab79854aaf25b620a52c39485849922f766";
      fetchSubmodules = false;
      sha256 = "sha256-hYKFidN3LHJg2NLM1EiJFki+0nqi1URnoLLPknUbFJY=";
    };
  };
}
