# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
}: {
  tree-sitter-eex = {
    pname = "tree-sitter-eex";
    version = "f742f2fe327463335e8671a87c0b9b396905d1d1";
    src = fetchFromGitHub {
      owner = "connorlay";
      repo = "tree-sitter-eex";
      rev = "f742f2fe327463335e8671a87c0b9b396905d1d1";
      fetchSubmodules = false;
      sha256 = "sha256-UPq62MkfGFh9m/UskoB9uBDIYOcotITCJXDyrbg/wKY=";
    };
  };
  tree-sitter-just = {
    pname = "tree-sitter-just";
    version = "8af0aab79854aaf25b620a52c39485849922f766";
    src = fetchFromGitHub {
      owner = "IndianBoy42";
      repo = "tree-sitter-just";
      rev = "8af0aab79854aaf25b620a52c39485849922f766";
      fetchSubmodules = false;
      sha256 = "sha256-hYKFidN3LHJg2NLM1EiJFki+0nqi1URnoLLPknUbFJY=";
    };
  };
  tree-sitter-norg = {
    pname = "tree-sitter-norg";
    version = "5d9c76b5c9927955f7c5d5d946397584e307f69f";
    src = fetchFromGitHub {
      owner = "nvim-neorg";
      repo = "tree-sitter-norg";
      rev = "5d9c76b5c9927955f7c5d5d946397584e307f69f";
      fetchSubmodules = false;
      sha256 = "sha256-x19Db6oVAJyNqtj0yMG9HAjzJrPuy52xp5k17r4j924=";
    };
  };
  tree-sitter-norg-meta = {
    pname = "tree-sitter-norg-meta";
    version = "4687b53e656b920cde6c0b9a7b9acf9a665cd838";
    src = fetchFromGitHub {
      owner = "nvim-neorg";
      repo = "tree-sitter-norg-meta";
      rev = "4687b53e656b920cde6c0b9a7b9acf9a665cd838";
      fetchSubmodules = false;
      sha256 = "sha256-+NInywA8KOfAVnetuRW/9GJIqFWijrMr23dhZx4b6EQ=";
    };
  };
  tree-sitter-norg-table = {
    pname = "tree-sitter-norg-table";
    version = "f354ea343b8803948e6e1df36eb586e31c529900";
    src = fetchFromGitHub {
      owner = "nvim-neorg";
      repo = "tree-sitter-norg-table";
      rev = "f354ea343b8803948e6e1df36eb586e31c529900";
      fetchSubmodules = false;
      sha256 = "sha256-xTH4LmqhtfyN9JGQdquJLQz1McZQItdEY5HpJxbuYC0=";
    };
  };
}
