# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
}: {
  tree-sitter-eex = {
    pname = "tree-sitter-eex";
    version = "f742f2fe327463335e8671a87c0b9b396905d1d1";
    src = fetchFromGitHub {
      owner = "connorlay";
      repo = "tree-sitter-eex";
      rev = "f742f2fe327463335e8671a87c0b9b396905d1d1";
      fetchSubmodules = false;
      sha256 = "sha256-UPq62MkfGFh9m/UskoB9uBDIYOcotITCJXDyrbg/wKY=";
    };
  };
  tree-sitter-just = {
    pname = "tree-sitter-just";
    version = "8af0aab79854aaf25b620a52c39485849922f766";
    src = fetchFromGitHub {
      owner = "IndianBoy42";
      repo = "tree-sitter-just";
      rev = "8af0aab79854aaf25b620a52c39485849922f766";
      fetchSubmodules = false;
      sha256 = "sha256-hYKFidN3LHJg2NLM1EiJFki+0nqi1URnoLLPknUbFJY=";
    };
  };
  tree-sitter-norg = {
    pname = "tree-sitter-norg";
    version = "8ad20059c6f128861c4506fff866150ffee1d6f4";
    src = fetchFromGitHub {
      owner = "nvim-neorg";
      repo = "tree-sitter-norg";
      rev = "8ad20059c6f128861c4506fff866150ffee1d6f4";
      fetchSubmodules = false;
      sha256 = "sha256-1cKH3k/nbZhZleINZ91M+glG1m2SlBJR/AP7mz/SAvI=";
    };
  };
  tree-sitter-norg-meta = {
    pname = "tree-sitter-norg-meta";
    version = "8e1a9008eb9492e95eb9a65ab0ec0419cfa9c4c7";
    src = fetchFromGitHub {
      owner = "nvim-neorg";
      repo = "tree-sitter-norg-meta";
      rev = "8e1a9008eb9492e95eb9a65ab0ec0419cfa9c4c7";
      fetchSubmodules = false;
      sha256 = "sha256-1gOTQdqB/TpaJ2ClNY+/Gqsj7TkCgv9CNiX97oF8PGo=";
    };
  };
  tree-sitter-norg-table = {
    pname = "tree-sitter-norg-table";
    version = "f354ea343b8803948e6e1df36eb586e31c529900";
    src = fetchFromGitHub {
      owner = "nvim-neorg";
      repo = "tree-sitter-norg-table";
      rev = "f354ea343b8803948e6e1df36eb586e31c529900";
      fetchSubmodules = false;
      sha256 = "sha256-xTH4LmqhtfyN9JGQdquJLQz1McZQItdEY5HpJxbuYC0=";
    };
  };
}
