# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
}: {
  LuaSnip-snippets-nvim = {
    pname = "LuaSnip-snippets-nvim";
    version = "d7e40e4cce622eab2316607dbcd8d6039bcb9fe0";
    src = fetchFromGitHub {
      owner = "molleweide";
      repo = "LuaSnip-snippets.nvim";
      rev = "d7e40e4cce622eab2316607dbcd8d6039bcb9fe0";
      fetchSubmodules = false;
      sha256 = "sha256-iFpk2dmcdF3krwem0Agl044ML2syw61wWPX7ldz4bhg=";
    };
  };
  elixir-nvim = {
    pname = "elixir-nvim";
    version = "2cb7c410346cb4f5b42b505b0e5cb036153973eb";
    src = fetchFromGitHub {
      owner = "mhanberg";
      repo = "elixir.nvim";
      rev = "2cb7c410346cb4f5b42b505b0e5cb036153973eb";
      fetchSubmodules = false;
      sha256 = "sha256-+sSoIKSSUD+ypDjPOn3dN5kG/IBACMOicF23nlBsO5I=";
    };
  };
  neoconf = {
    pname = "neoconf";
    version = "c808afff84ed3578c4598b9301e0d600a6044e40";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "neoconf.nvim";
      rev = "c808afff84ed3578c4598b9301e0d600a6044e40";
      fetchSubmodules = false;
      sha256 = "sha256-ZAIYKwQmgzgOo3YvD46m/NHZOl1Vdmi4mE+USi/rfaA=";
    };
  };
  neorg = {
    pname = "neorg";
    version = "a79bf5969e27a3f1f1478c9b05c187815f2b2390";
    src = fetchFromGitHub {
      owner = "nvim-neorg";
      repo = "neorg";
      rev = "a79bf5969e27a3f1f1478c9b05c187815f2b2390";
      fetchSubmodules = false;
      sha256 = "sha256-MDXf5LYTYEKZHrhWCJBp+0BGEZG1Qz35/0SCoosTHKk=";
    };
  };
  neorg-telescope = {
    pname = "neorg-telescope";
    version = "8d15129818c5dc224be97c9c6350d3386addeac8";
    src = fetchFromGitHub {
      owner = "nvim-neorg";
      repo = "neorg-telescope";
      rev = "8d15129818c5dc224be97c9c6350d3386addeac8";
      fetchSubmodules = false;
      sha256 = "sha256-KDEziW99VyW2RjGV0+JaLSXXZ66WSNVPBNaw6N7Fri0=";
    };
  };
  other-nvim = {
    pname = "other-nvim";
    version = "9afecea37c9b5ffed65a21de9e585d548de7778a";
    src = fetchFromGitHub {
      owner = "rgroli";
      repo = "other.nvim";
      rev = "9afecea37c9b5ffed65a21de9e585d548de7778a";
      fetchSubmodules = false;
      sha256 = "sha256-df/L8ZOdjkviE6WRRe7uon82hlUb+yYDdtiN3pJ5OBs=";
    };
  };
  pretty-fold-nvim = {
    pname = "pretty-fold-nvim";
    version = "a7d8b424abe0eedf50116c460fbe6dfd5783b1d5";
    src = fetchFromGitHub {
      owner = "anuvyklack";
      repo = "pretty-fold.nvim";
      rev = "a7d8b424abe0eedf50116c460fbe6dfd5783b1d5";
      fetchSubmodules = false;
      sha256 = "sha256-PQPZw0qXwMtpVE4uSxR3xUvkHE9iG4T+ZwgV6H9pUjo=";
    };
  };
  vim-just = {
    pname = "vim-just";
    version = "838c9096d4c5d64d1000a6442a358746324c2123";
    src = fetchFromGitHub {
      owner = "NoahTheDuke";
      repo = "vim-just";
      rev = "838c9096d4c5d64d1000a6442a358746324c2123";
      fetchSubmodules = false;
      sha256 = "sha256-DSC47z2wOEXvo2kGO5JtmR3hyHPiYXrkX7MgtagV5h4=";
    };
  };
  vim-rdf = {
    pname = "vim-rdf";
    version = "e2af9a7614a9fb9c3fc419135d41700426cad0db";
    src = fetchFromGitHub {
      owner = "niklasl";
      repo = "vim-rdf";
      rev = "e2af9a7614a9fb9c3fc419135d41700426cad0db";
      fetchSubmodules = false;
      sha256 = "sha256-qpuF4vSU0VaQrcrYgksYb6z2oRyXOKirkzAgBCdUomQ=";
    };
  };
}
