# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
}: {
  elixir-nvim = {
    pname = "elixir-nvim";
    version = "06614fa79ae2b914ded09e72f5574df1fc1024b4";
    src = fetchFromGitHub {
      owner = "mhanberg";
      repo = "elixir.nvim";
      rev = "06614fa79ae2b914ded09e72f5574df1fc1024b4";
      fetchSubmodules = false;
      sha256 = "sha256-uWTvfMBKJs2DvknOqKaOYKHBgCZZ+mb93WrSfpZZ7Vs=";
    };
  };
  other-nvim = {
    pname = "other-nvim";
    version = "a2ae9e03d08c6c5e8f60cc1db58cbf4ada2ae338";
    src = fetchFromGitHub {
      owner = "rgroli";
      repo = "other.nvim";
      rev = "a2ae9e03d08c6c5e8f60cc1db58cbf4ada2ae338";
      fetchSubmodules = false;
      sha256 = "sha256-knAHH4cxCxBTCZb54BERyR3l6+uhzZ3k9yPSzAl/4W0=";
    };
  };
  pretty-fold-nvim = {
    pname = "pretty-fold-nvim";
    version = "a7d8b424abe0eedf50116c460fbe6dfd5783b1d5";
    src = fetchFromGitHub {
      owner = "anuvyklack";
      repo = "pretty-fold.nvim";
      rev = "a7d8b424abe0eedf50116c460fbe6dfd5783b1d5";
      fetchSubmodules = false;
      sha256 = "sha256-PQPZw0qXwMtpVE4uSxR3xUvkHE9iG4T+ZwgV6H9pUjo=";
    };
  };
  vim-just = {
    pname = "vim-just";
    version = "312615d5b4c4aa2595d697faca5af345ba8fe102";
    src = fetchFromGitHub {
      owner = "NoahTheDuke";
      repo = "vim-just";
      rev = "312615d5b4c4aa2595d697faca5af345ba8fe102";
      fetchSubmodules = false;
      sha256 = "sha256-8qGFYRoVIiGB240wdM0o9hCMt65Gg4qIh7pvmW3DghU=";
    };
  };
}
