# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
}: {
  elixir-nvim = {
    pname = "elixir-nvim";
    version = "62a312ef130bd22e99686dc5e10bb6a677a4d9bd";
    src = fetchFromGitHub {
      owner = "mhanberg";
      repo = "elixir.nvim";
      rev = "62a312ef130bd22e99686dc5e10bb6a677a4d9bd";
      fetchSubmodules = false;
      sha256 = "sha256-2UVJ8pyhu42UzGvwD/WSjOwhYYYgGl4ttj2D9F1qA90=";
    };
  };
  neorg = {
    pname = "neorg";
    version = "49d0b5a3acf94f349a7351042d42933bf1047ad5";
    src = fetchFromGitHub {
      owner = "nvim-neorg";
      repo = "neorg";
      rev = "49d0b5a3acf94f349a7351042d42933bf1047ad5";
      fetchSubmodules = false;
      sha256 = "sha256-j7C8/Zz/UzjwvPbFzYnoeAnnhZPVuKGGIC2h6rYs/Kg=";
    };
  };
  neorg-telescope = {
    pname = "neorg-telescope";
    version = "b61ff59c7008fabe0ead42adb1a1498aec2b6fe1";
    src = fetchFromGitHub {
      owner = "nvim-neorg";
      repo = "neorg-telescope";
      rev = "b61ff59c7008fabe0ead42adb1a1498aec2b6fe1";
      fetchSubmodules = false;
      sha256 = "sha256-DzdmTQBNMJpp2Pnjy32a7AJrST+GLb0Hy5+tTjd8a5Q=";
    };
  };
  other-nvim = {
    pname = "other-nvim";
    version = "a2ae9e03d08c6c5e8f60cc1db58cbf4ada2ae338";
    src = fetchFromGitHub {
      owner = "rgroli";
      repo = "other.nvim";
      rev = "a2ae9e03d08c6c5e8f60cc1db58cbf4ada2ae338";
      fetchSubmodules = false;
      sha256 = "sha256-knAHH4cxCxBTCZb54BERyR3l6+uhzZ3k9yPSzAl/4W0=";
    };
  };
  pretty-fold-nvim = {
    pname = "pretty-fold-nvim";
    version = "a7d8b424abe0eedf50116c460fbe6dfd5783b1d5";
    src = fetchFromGitHub {
      owner = "anuvyklack";
      repo = "pretty-fold.nvim";
      rev = "a7d8b424abe0eedf50116c460fbe6dfd5783b1d5";
      fetchSubmodules = false;
      sha256 = "sha256-PQPZw0qXwMtpVE4uSxR3xUvkHE9iG4T+ZwgV6H9pUjo=";
    };
  };
  vim-just = {
    pname = "vim-just";
    version = "312615d5b4c4aa2595d697faca5af345ba8fe102";
    src = fetchFromGitHub {
      owner = "NoahTheDuke";
      repo = "vim-just";
      rev = "312615d5b4c4aa2595d697faca5af345ba8fe102";
      fetchSubmodules = false;
      sha256 = "sha256-8qGFYRoVIiGB240wdM0o9hCMt65Gg4qIh7pvmW3DghU=";
    };
  };
}
