name: "Test"
on:
  pull_request:
  push:
    branches:
      - 'develop'
      - 'feature/ci'
  schedule:
    # 10:30am UTC, 4:30am CST
    - cron: '30 10 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: shanesveller-neovim
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    # - run: |
    #     nix flake archive --json \
    #       | jq -r '.path,(.inputs|to_entries[].value.path)' \
    #       | cachix push shanesveller-neovim 
    #   env:
    #     CACHIX_AUTH_TOKEN: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix -L build .#neovim
    - run: nix -L build .#neovimConfigured
    - run: |
        nix build --json \
          | jq -r '.[].outputs | to_entries[].value' \
          | cachix push shanesveller-neovim
      env:
        CACHIX_AUTH_TOKEN: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      if: github.ref == 'refs/heads/develop'
